export const LOAD_TYPES_REQUEST = 'LOAD_TYPES_REQUEST'
export const LOAD_TYPES_SUCCESS = 'LOAD_TYPES_SUCCESS'
export const LOAD_TYPES_FAILURE = 'LOAD_TYPES_FAILURE'

export const LOAD_TYPE_REQUEST = 'LOAD_TYPE_REQUEST'
export const LOAD_TYPE_SUCCESS = 'LOAD_TYPE_SUCCESS'
export const LOAD_TYPE_FAILURE = 'LOAD_TYPE_FAILURE'

export const CREATE_TYPE_REQUEST = 'CREATE_TYPE_REQUEST'
export const CREATE_TYPE_SUCCESS = 'CREATE_TYPE_SUCCESS'
export const CREATE_TYPE_FAILURE = 'CREATE_TYPE_FAILURE'

export const UPDATE_TYPE_REQUEST = 'UPDATE_TYPE_REQUEST'
export const UPDATE_TYPE_SUCCESS = 'UPDATE_TYPE_SUCCESS'
export const UPDATE_TYPE_FAILURE = 'UPDATE_TYPE_FAILURE'

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const LOAD_ARTICLES_REQUEST = 'LOAD_ARTICLES_REQUEST'
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS'
export const LOAD_ARTICLES_FAILURE = 'LOAD_ARTICLES_FAILURE'

export const LOAD_ARTICLE_REQUEST = 'LOAD_ARTICLE_REQUEST'
export const LOAD_ARTICLE_SUCCESS = 'LOAD_ARTICLE_SUCCESS'
export const LOAD_ARTICLE_FAILURE = 'LOAD_ARTICLE_FAILURE'

export const CREATE_ARTICLE_REQUEST = 'CREATE_ARTICLE_REQUEST'
export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS'
export const CREATE_ARTICLE_FAILURE = 'CREATE_ARTICLE_FAILURE'

export const UPDATE_ARTICLE_REQUEST = 'UPDATE_ARTICLE_REQUEST'
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS'
export const UPDATE_ARTICLE_FAILURE = 'UPDATE_ARTICLE_FAILURE'

export const LOAD_BUGS_REQUEST = 'LOAD_BUGS_REQUEST'
export const LOAD_BUGS_SUCCESS = 'LOAD_BUGS_SUCCESS'
export const LOAD_BUGS_FAILURE = 'LOAD_BUGS_FAILURE'

export const LOAD_BUG_REQUEST = 'LOAD_BUG_REQUEST'
export const LOAD_BUG_SUCCESS = 'LOAD_BUG_SUCCESS'
export const LOAD_BUG_FAILURE = 'LOAD_BUG_FAILURE'

export const CREATE_BUG_REQUEST = 'CREATE_BUG_REQUEST'
export const CREATE_BUG_SUCCESS = 'CREATE_BUG_SUCCESS'
export const CREATE_BUG_FAILURE = 'CREATE_BUG_FAILURE'

export const UPDATE_BUG_REQUEST = 'UPDATE_BUG_REQUEST'
export const UPDATE_BUG_SUCCESS = 'UPDATE_BUG_SUCCESS'
export const UPDATE_BUG_FAILURE = 'UPDATE_BUG_FAILURE'

export const LOAD_PICTURES_REQUEST = 'LOAD_PICTURES_REQUEST'
export const LOAD_PICTURES_SUCCESS = 'LOAD_PICTURES_SUCCESS'
export const LOAD_PICTURES_FAILURE = 'LOAD_PICTURES_FAILURE'

export const CREATE_PICTURE_REQUEST = 'CREATE_PICTURE_REQUEST'
export const CREATE_PICTURE_SUCCESS = 'CREATE_PICTURE_SUCCESS'
export const CREATE_PICTURE_FAILURE = 'CREATE_PICTURE_FAILURE'
